### ISSUE TITLE
Add HTML email body examples to examples.py

### ISSUE THREAD

**Issue by barrybarrette** [whitebarry/py-emails#3]
The library currently supports HTML email bodies via the `body_type` argument to the constructor and the `body_type` key of the template dictionary. The `examples.py` file does not currently showcase this functionality and it would be useful for consumers to see how it works by example.

**Comment by Vipul-Bajaj** [comment]
Hi @barrybarrette,
I would like to work on this issue.

**Comment by barrybarrette** [comment]
Hi @Vipul-Bajaj,

Thanks for your contribution! I have just 2 things I would like you to address which I have left as comments on your PR. If you can go ahead and address those I'll be happy to get this merged in!

**Comment by Vipul-Bajaj** [comment]
> Hi @Vipul-Bajaj,
> 
> Thanks for your contribution! I have just 2 things I would like you to address which I have left as comments on your PR. If you can go ahead and address those I'll be happy to get this merged in!

Hi @barrybarrette ,
I have addressed both the issues, you can have the look.

**Comment by barrybarrette** [comment]
Merged, thanks @Vipul-Bajaj!

**Comment by Vipul-Bajaj** [comment]
hi @barrybarrette ,
Happy to help.
Can you please add label `hacktoberfest-accepted` to the PR as, it shows the project is not participating in my profile.
Thanks in advance.

**Comment by barrybarrette** [comment]
@Vipul-Bajaj sorry about that, I was not aware we had to opt in this year! I've updated the repo with the `hacktoberfest` topic and your PR should be counted shortly. If it is not showing up within a few hours let me know and I'll mark the PR manually. Thanks again.

**Comment by Vipul-Bajaj** [comment]
Np @barrybarrette. It is being counted now. Thanks :)
